import { useEffect, useRef, useState } from "react"
import { Plus, Mic, Send, Globe, Code2, Languages, Eye, Volume2, Paperclip } from "lucide-react"
import { Orb } from "@/components/maya/Orb"
import { ExecCard } from "@/components/maya/ExecCard"
import { useAgentRun } from "@/hooks/useAgentRun"
import { agentAPI } from "@/lib/api"
type Msg = { role: "user"|"maya"; text: string }
const TOOLS = [{ icon: Globe, label: "Web search" }, { icon: Code2, label: "Run code" }, { icon: Languages, label: "Translate" }, { icon: Eye, label: "Analyze image" }, { icon: Volume2, label: "Speak" }, { icon: Paperclip, label: "Attach file" }]
export function Chat({ admin }: { admin: boolean }) {
  const [mode, setMode] = useState<"Agent"|"Chat"|"Think">("Agent")
  const [msgs, setMsgs] = useState<Msg[]>([{ role: "maya", text: "Hi, I'm Maya. Give me a goal — you'll see me work through it live." }])
  const [input, setInput] = useState(""); const [toolsOpen, setToolsOpen] = useState(false); const [busy, setBusy] = useState(false)
  const run = useAgentRun(); const endRef = useRef<HTMLDivElement>(null); const done = useRef(false)
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }) }, [msgs, run.task, run.approval])
  useEffect(() => { if ((run.status === "done" || run.status === "failed") && run.task && !done.current) { done.current = true; setMsgs((m) => [...m, { role: "maya", text: run.status === "failed" ? (run.task!.error || "Stopped.") : (run.task!.result || "Done.") }]); setBusy(false) } }, [run.status, run.task])
  const send = async () => {
    const q = input.trim(); if (!q || busy) return
    setInput(""); setToolsOpen(false); setMsgs((m) => [...m, { role: "user", text: q }]); setBusy(true); done.current = false
    if (mode === "Agent") { run.reset(); done.current = false; run.start(q) }
    else if (mode === "Think") { try { const r = (await agentAPI.think(q)) as any; setMsgs((m) => [...m, { role: "maya", text: r?.result || r?.answer || JSON.stringify(r) }]) } catch (e: any) { setMsgs((m) => [...m, { role: "maya", text: `Error: ${e?.message || e}` }]) } finally { setBusy(false) } }
    else { let acc = ""; setMsgs((m) => [...m, { role: "maya", text: "" }]); try { await agentAPI.streamChat(q, (d) => { acc += d; setMsgs((m) => { const c = [...m]; c[c.length - 1] = { role: "maya", text: acc }; return c }) }) } catch { try { const r = (await agentAPI.chat(q)) as any; setMsgs((m) => { const c = [...m]; c[c.length - 1] = { role: "maya", text: r?.response || r?.reply || "…" }; return c }) } catch (e: any) { setMsgs((m) => { const c = [...m]; c[c.length - 1] = { role: "maya", text: `Error: ${e?.message || e}` }; return c }) } } finally { setBusy(false) } }
  }
  const showCard = mode === "Agent" && run.task
  return (<div className="flex flex-col h-full max-w-3xl mx-auto w-full"><div className="px-4 md:px-6 pt-4 pb-2 flex items-center gap-3"><div className="m-seg" role="tablist">{(["Chat", "Agent", "Think"] as const).map((m) => (<button key={m} data-on={mode === m} onClick={() => setMode(m)} className="m-focus">{m}</button>))}</div><span className="text-xs m-muted hidden sm:block">{mode === "Agent" ? "Runs a task live" : mode === "Think" ? "Deep reasoning" : "Quick chat"}</span></div>
  <div className="flex-1 overflow-y-auto m-hide-sb px-4 md:px-6 py-4 space-y-4">{msgs.map((m, i) => (<div key={i} className={`flex gap-3 m-rise ${m.role === "user" ? "flex-row-reverse" : ""}`}>{m.role === "maya" ? <Orb size={30} /> : <div className="rounded-full m-sunken m-bd flex items-center justify-center text-xs font-semibold m-muted" style={{ width: 30, height: 30 }}>You</div>}{m.text && <div className={`px-4 py-2.5 text-[15px] ${m.role === "user" ? "m-accent-bg" : "m-surface m-bd"}`} style={{ maxWidth: "80%", borderRadius: 18, borderTopLeftRadius: m.role === "maya" ? 6 : 18, borderTopRightRadius: m.role === "user" ? 6 : 18 }}>{m.text}</div>}</div>))}{showCard && run.task && <ExecCard task={run.task} approval={run.approval} admin={admin} onApprove={run.approve} onReject={run.reject} />}{run.error && <div className="text-[13px]" style={{ color: "#EF4444", marginLeft: 42 }}>{run.error}</div>}<div ref={endRef} /></div>
  <div className="px-4 md:px-6 pb-5 pt-2">{toolsOpen && <div className="m-card m-shadow p-2 mb-2 grid grid-cols-3 gap-1 m-rise">{TOOLS.map((t) => (<button key={t.label} onClick={() => { setInput((v) => v + (v ? " " : "") + t.label + ": "); setToolsOpen(false) }} className="m-nav m-focus m-press"><t.icon size={16} className="m-accent" /><span className="text-[13px]">{t.label}</span></button>))}</div>}<div className="m-card m-shadow-sm p-2 flex items-end gap-2"><button aria-label="tools" onClick={() => setToolsOpen((v) => !v)} className="m-accent-soft rounded-xl p-2.5 m-press m-focus" style={{ transform: toolsOpen ? "rotate(45deg)" : "none", transition: "transform .18s" }}><Plus size={18} className="m-accent" /></button><textarea value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send() } }} rows={1} placeholder="Message Maya…" className="flex-1 bg-transparent resize-none outline-none text-[15px] m-ink py-2" style={{ minHeight: 24, maxHeight: 128 }} /><button aria-label="voice" className="rounded-xl p-2.5 m-press m-focus m-muted"><Mic size={18} /></button><button aria-label="send" onClick={send} disabled={!input.trim() || busy} className="m-accent-bg rounded-xl p-2.5 m-press m-focus" style={{ opacity: !input.trim() || busy ? .4 : 1 }}><Send size={18} /></button></div></div></div>)
}
